In [1]:
import pandas as pd

from src.cml.utils import load_cml_dataset
from src.radar.utils import load_radar_dataset, process_radar_dataset, load_processed_dataset
import torch

%load_ext autoreload
%autoreload 2

# CML

In [ ]:
cml_df = load_cml_dataset("combined_microwave_link_data_2024_2025.nc")

In [ ]:
cml_data_df, cml_coordinates_df = cml_df

In [ ]:
cml_data_df.drop(columns=['link_id', 'station', 'timestamp', 'resource_name'], inplace=True)

In [ ]:
cml_df

In [ ]:
cml_df

In [ ]:
cml_data_df

In [ ]:
cml_data_df

In [ ]:
cml_data_df.drop(columns=['source_site_id', 'sink_site_id'], inplace=True)
tensor = torch.tensor(cml_data_df.values)

In [ ]:
tensor[:, 1]

In [ ]:
for i in range(tensor.shape[1]):
  nan_count = torch.isnan(tensor[:, i]).sum()
  print(nan_count)

In [ ]:
nan_count

# RADAR

In [5]:
process_radar_dataset("database/area_23", crop_bounds={"left": 103.6, "right": 104.1, "top": 1.5, "bottom": 1.19})

,timestamp,data,bounds,crs,transform
0,2024-09-08 07:00:00,"[[6.2085085, 7.1068215, 3.3629353, 1.9941579, ...","(103.593, 1.192, 104.09700000000001, 1.507)","(proj, datum, no_defs)","(0.1, 0.0, 103.593, 0.0, -0.1, 1.507, 0.0, 0.0..."
1,2024-09-08 10:00:00,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","(103.593, 1.192, 104.09700000000001, 1.507)","(proj, datum, no_defs)","(0.1, 0.0, 103.593, 0.0, -0.1, 1.507, 0.0, 0.0..."
2,2024-09-08 14:00:00,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","(103.593, 1.192, 104.09700000000001, 1.507)","(proj, datum, no_defs)","(0.1, 0.0, 103.593, 0.0, -0.1, 1.507, 0.0, 0.0..."
3,2024-09-08 03:00:00,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","(103.593, 1.192, 104.09700000000001, 1.507)","(proj, datum, no_defs)","(0.1, 0.0, 103.593, 0.0, -0.1, 1.507, 0.0, 0.0..."
4,2024-09-08 14:15:00,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","(103.593, 1.192, 104.09700000000001, 1.507)","(proj, datum, no_defs)","(0.1, 0.0, 103.593, 0.0, -0.1, 1.507, 0.0, 0.0..."
...,...,...,...,...,...
31498,2024-07-26 19:45:00,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","(103.593, 1.192, 104.09700000000001, 1.507)","(proj, datum, no_defs)","(0.1, 0.0, 103.593, 0.0, -0.1, 1.507, 0.0, 0.0..."
31499,2024-07-26 20:45:00,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","(103.593, 1.192, 104.09700000000001, 1.507)","(proj, datum, no_defs)","(0.1, 0.0, 103.593, 0.0, -0.1, 1.507, 0.0, 0.0..."
31500,2024-07-26 18:15:00,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","(103.593, 1.192, 104.09700000000001, 1.507)","(proj, datum, no_defs)","(0.1, 0.0, 103.593, 0.0, -0.1, 1.507, 0.0, 0.0..."
31501,2024-07-26 21:15:00,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","(103.593, 1.192, 104.09700000000001, 1.507)","(proj, datum, no_defs)","(0.1, 0.0, 103.593, 0.0, -0.1, 1.507, 0.0, 0.0..."
31502,2024-07-26 09:30:00,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","(103.593, 1.192, 104.09700000000001, 1.507)","(proj, datum, no_defs)","(0.1, 0.0, 103.593, 0.0, -0.1, 1.507, 0.0, 0.0..."

In [6]:
processed_dataset_Df = load_processed_dataset("database/processed_radar_dataset.pkl")

In [7]:
processed_dataset_Df

,timestamp,data,bounds,crs,transform
0,2024-09-08 07:00:00,"[[6.2085085, 7.1068215, 3.3629353, 1.9941579, ...","(103.593, 1.192, 104.09700000000001, 1.507)","(proj, datum, no_defs)","(0.1, 0.0, 103.593, 0.0, -0.1, 1.507, 0.0, 0.0..."
1,2024-09-08 10:00:00,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","(103.593, 1.192, 104.09700000000001, 1.507)","(proj, datum, no_defs)","(0.1, 0.0, 103.593, 0.0, -0.1, 1.507, 0.0, 0.0..."
2,2024-09-08 14:00:00,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","(103.593, 1.192, 104.09700000000001, 1.507)","(proj, datum, no_defs)","(0.1, 0.0, 103.593, 0.0, -0.1, 1.507, 0.0, 0.0..."
3,2024-09-08 03:00:00,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","(103.593, 1.192, 104.09700000000001, 1.507)","(proj, datum, no_defs)","(0.1, 0.0, 103.593, 0.0, -0.1, 1.507, 0.0, 0.0..."
4,2024-09-08 14:15:00,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","(103.593, 1.192, 104.09700000000001, 1.507)","(proj, datum, no_defs)","(0.1, 0.0, 103.593, 0.0, -0.1, 1.507, 0.0, 0.0..."
...,...,...,...,...,...
31498,2024-07-26 19:45:00,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","(103.593, 1.192, 104.09700000000001, 1.507)","(proj, datum, no_defs)","(0.1, 0.0, 103.593, 0.0, -0.1, 1.507, 0.0, 0.0..."
31499,2024-07-26 20:45:00,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","(103.593, 1.192, 104.09700000000001, 1.507)","(proj, datum, no_defs)","(0.1, 0.0, 103.593, 0.0, -0.1, 1.507, 0.0, 0.0..."
31500,2024-07-26 18:15:00,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","(103.593, 1.192, 104.09700000000001, 1.507)","(proj, datum, no_defs)","(0.1, 0.0, 103.593, 0.0, -0.1, 1.507, 0.0, 0.0..."
31501,2024-07-26 21:15:00,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","(103.593, 1.192, 104.09700000000001, 1.507)","(proj, datum, no_defs)","(0.1, 0.0, 103.593, 0.0, -0.1, 1.507, 0.0, 0.0..."
31502,2024-07-26 09:30:00,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","(103.593, 1.192, 104.09700000000001, 1.507)","(proj, datum, no_defs)","(0.1, 0.0, 103.593, 0.0, -0.1, 1.507, 0.0, 0.0..."